photop/photoapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from photoapp import views
from django.urls import path

app_name = 'photoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:photo_id>/', views.detail, name='detail'),
]

photop/photop/urls.py
#from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photos/', include('photoapp.urls'))
]

photop/photoapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.


class Photo(models.Model):
    name = models.CharField(max_length=100)
    creator = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    '''
    whenever you make changes to this DB, do this at terminal 
    python manage.py makemigrations photoapp
    python manage.py sqlmigrate photoapp 0001
    python manage.py migrate
    
    '''

    def __str__(self):
        return self.name + '-' + self.creator

photop/photoapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from .models import Photo
from django.template import loader
from django.shortcuts import render
from django.http import Http404


# Create your views here.

def index(request):
    all_photos = Photo.objects.all()
    '''
    html = ''
    for photo in all_photos:
        url = '/photos/' + str(photo.id) + '/'
        html += ' <a href="' + url + '">' + str(photo.name) + '</a><br>'
    #Deleted this and replaced with html template
    '''
    template = loader.get_template('photoapp/index.html')
    context = {
        'all_photos': all_photos
    }
    # return HttpResponse(template.render(context,request))  # instead of HttpResponse, use render()
    return render(request, 'photoapp/index.html', context)


def detail(request, photo_id):
    # return HttpResponse("<h2> This is the page for Photo" + str(photo_id) + "</h2>")  #This is static
    try:
        photo = Photo.objects.get(id=photo_id)
    except Photo.DoesNotExist:
        raise Http404('Photo not found')
    return render(request, 'photoapp/detail.html', {'photo': photo})

photop/photoapp/templates/photoapp/detail.html
<h1>{{photo.name}}</h1>
<h2>{{photo.creator}}</h2>
<h3>{{photo.price}}</h3>

photop/photoapp/templates/photoapp/index.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'photoapp/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>

    <body>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'photoapp:index' %}">PhotoWebsite</a>
                <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'photoapp:index' %}">
                            <span class="glyphicon glyphicon-camera" aria-hidden="true"></span>&nbsp; Images
                        </a>
                    </li>
                </ul>
            </div>
            </div>

        </nav>
        <ul>
            {% for photo in all_photos %}
                <li>
                    <a href="{% url 'photoapp:detail' photo.id %}">{{photo.name}}</a>
                </li>
            {% endfor %}
        </ul>
    </body>
</html>